reshenie
js-tasks-ru/jsbasic-20220310_yakubouskajarenata pull request #4
Opened 2022-04-08 16:17 UTC by YaAliaksandr

2022-04-08 16:18 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-09 20:53 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-04-09 21:09 UTC, YaAliaksandr commented
посмотрите пожалуйста решение задачи 4.3 (я его закомментировал) ---- хочу его решить именно через реализацию  того кода который я закомментировал в самом начале, почему ругается на  21-ой строке на "hasAttribute" , если  коммичу этот блок кода тогда ругается на 32 строку --- на 'textContent'

2022-04-11 19:27 UTC, koalex requested changes
Исправить замечания

2022-04-11 19:27 UTC, koalex commented on 2-module/2-task/index.js
> +	if (objToArrow.length < 1) {
`return objToArrow.length < 1;`

2022-04-11 19:27 UTC, koalex commented on 2-module/3-task/index.js
> +		return calculator.value1 = arg1, calculator.value2 = arg2;
нужно через `this`

2022-04-11 19:27 UTC, koalex commented on 3-module/1-task/index.js
> +				usersNameArray.push(`${users[keyUsers][keyObjectUsers]}`);
Нужно решить через [map](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/map)

2022-04-11 19:27 UTC, koalex commented on 3-module/5-task/index.js
> +	result.max = sortStrWithNumbers[sortStrWithNumbers.length - 1];
[Math.max](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Math/max) и [Math.min](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Math/min)

2022-04-11 19:27 UTC, koalex commented on 4-module/3-task/index.js
> +				table.rows[r].cells[c].parentElement.setAttribute('hidden', true);
table.rows[r].cells[c].parentElement.hidden = true;

2022-12-08 21:12 UTC, closed without merging